// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace TtGameplayTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Weapon_Fire);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Weapon_Reload);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Weapon_Equip);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Ammo_Equip);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ammo_Regular);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ammo_Fire);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ammo_Water);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ammo_Healing);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_Burning);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Data_Damage_Physical);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Data_Damage_Fire);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Data_Damage_Water);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Data_Healing);
}
